# Generated by Django 5.2.5 on 2025-08-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_seed_servicetags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetag',
            options={'ordering': ['title'], 'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='servicetag',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='servicetag',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Фотография (аватар)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('provider', 'Банные услуги'), ('builder', 'Строительство бань'), ('seller', 'Продажа товаров'), ('enthusiast', 'Люблю попариться')], max_length=20, verbose_name='Тип пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.servicetag', verbose_name='Специализации'),
        ),
    ]
